npm i --force
echo "stopping canister"
echo "---------Stoping dfx----------"
dfx stop
echo "---------Starting dfx----------"
dfx start --clean --background
echo "---------Deploying Backend Canister----------"
dfx deploy backend
userCanister=$(dfx canister call backend createHelloServiceCanisterByGroup userCanister | grep -oP '(?<=\")(.*?)(?=\")')
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing user Canister and Current number cycles available in user Canister , using principal of idenitity in terminal----------"
dfx canister call $userCanister getCycles
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. small data, using principal of idenitity in terminal----------"
dfx canister call $userCanister loopClass '("Indian Cousenre","Florida USA","Small And huge room","200000 rooms","$45444444444444 night")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 2 ie .. medium lenght data, using principal of idenitity in terminal ----------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister loopClass '("Black Villa","Lcals Anders ","Huge Rooms And Huge Bathroom and Huuge Interreddd Intrea catorer ddc jnfnvf jnn EDNnj Work not found ton  fhnnc jnnfvfv  mfffnvfvnf jfrjvjfvfv ffnfnvfv ","A lonf tjsdf has been Insterted","$50000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel using data of type 1 ie .. Huge size data, using principal of idenitity in terminal ----------"
dfx canister call $userCanister loopClass '("Msteroal ","Ludhiana Punjab India Earth ","Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now Numerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right nowNumerical data has to be small motoko is var no one can understand very beautifull to hang behing and understand but random thought in midnight, Knights are dangerous because of ghost no is protecting and very diffuct to understand what to do right now","20,000 rooms avilable","$10000")'
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing Canister and creating Hotel and getting Array of cycles consumed in every cycle call----------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo "---------Accessing user Canister and Current number cycles available in user Canister , using principal of idenitity in terminal----------"
dfx canister call $userCanister getCycles
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------"
dfx canister call $userCanister cycleAnalysis
echo " --------------------------------Above was the Array of cycles consumed in ever single process"
echo " --------------------------------"
echo " --------------------------------"
echo " --------------------------------Not stoping the dfx so that you could use other functions in the HotelCanister";
